# this file is here to facilitate development/testing
# $ docker compose up -d --build --force-recreate

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  backup:
    build:
      context: .
      args:
        ALPINE_VERSION: '3.18'
    environment:
      SCHEDULE: '@weekly'     # optional
      BACKUP_KEEP_DAYS: 1     # optional
      PASSPHRASE:             # optional
      S3_REGION:
      S3_ACCESS_KEY_ID:
      S3_SECRET_ACCESS_KEY:
      # file will be stored in $S3_ENDPOINT/$S3_BUCKET/$S3_PREFIX/$(date).dump
      S3_ENDPOINT:            # for S3 compatible providers
      S3_BUCKET:
      S3_PREFIX:              # could/be/a/path
      MONGO_HOST: mongo
      MONGO_DATABASE: test
      MONGO_PORT: 27017
      MONGO_USER: user
      MONGO_PASSWORD: password
      MONGODUMP_EXTRA_OPTS:
      MONGORESTORE_EXTRA_OPTS:

volumes:
  mongo_data:
